[project]
name = "robot-assistant-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "assemblyai>=0.52.0",
    "beautifulsoup4>=4.14.3",
    "chromadb>=1.5.0",
    "dotenv>=0.9.9",
    "langchain>=1.2.10",
    "langchain-community>=0.4.1",
    "langchain-groq>=1.1.2",
    "langchain-huggingface>=1.2.0",
    "langchain-openai>=1.1.9",
    "langgraph>=1.0.4",
    "numpy>=2.3.5",
    "pyaudio>=0.2.14",
    "pydub>=0.25.1",
    "pypdf>=6.7.0",
    "requests>=2.32.5",
]
